# Generated by Django 2.1.7 on 2019-03-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayooluwaoyewoscrumy', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
